---
title: "E8 revision 051518"
author: "Marissa Lee"
date: "5/15/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---


_________________________________________________________________
# 0. Import, clean, merge, load fxns
```{r libraries, echo=FALSE}
knitr::opts_chunk$set(cache=TRUE)

#LIBRARIES
library(plyr)
library(reshape2)
library(ggplot2) #plotting
library(ggthemes) #ggplot accessories
library(GGally) #????
library(gtable)
library(gridExtra) #for grid.arrange fxn
library(lme4) #for mixed-effects models
library(lmerTest) #for lmer p-values
library(vegan) #for adonis fxn to do perMANOVAs
library(lavaan) #for structural equation modeling
library(doBy) #the orderBy fxn
library(merTools)
#library(bpca) #for 3d plots
#load other libraries
library(car) #Anova()
library(QuantPsyc) #lm.beta()
library(semPlot)
library(piecewiseSEM)
#citation('piecewiseSEM')

#CUSTOM FUNCTIONS
source('CODE/fxn_reshapeHelpers.R')
source('CODE/fxn_PCAhelpers.R')
source('CODE/fxn_NMDShelpers.R')
source('CODE/fxn_ScaleFit_q2.R')
source('CODE/fxn_InvEffect.R') #calculate invasion effect in a mixed effects model
source('CODE/fxn_predictHelpers.R') #creates dataframes to feed into model predictions

#THEME
source('CODE/mytheme.R')

#IMPORT, CLEAN, MERGE
source('CODE/script_cleanMerge.R')
#saves plot 'pHist_depth.png'
#saves data 'data_a.txt' # aggregated mean(depth) for 2012 and 2013
#saves data 'data_d.txt' # removed variables that were only measured in 2011 (i.e. full soil depth 0-15cm measurements)

#decide what dataset to use
data.choice<-data_d

#summarize mv biomass
data.choice %>% 
  filter(variable=="mv_g.m2") %>%
  group_by(inv) %>%
  summarize(mean=mean(value))

```

_________________________________________________________________
# 0. Visualize data
```{r visualize, echo=FALSE}
source('CODE/script_visualize.R')
#saves the following plots:
#plot N variables - NMDS, PCA x plot points, site vectors
#all plot variables - NMDS, PCA x plot points, site vectors
#reference plot and site variables - NMDS, PCA
#saves the following tables:
#PCA loadings for plot N variables, all plot variablers, reference plot and site variables
```
